DROP TABLE IF EXISTS GENRES CASCADE;
DROP TABLE IF EXISTS AUTHORS CASCADE;
DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE genres (
  ID BIGSERIAL NOT NULL,
  GENRE_NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE authors (
  ID BIGSERIAL NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE books (
  ID BIGSERIAL NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  GENRE_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  foreign key (AUTHOR_ID) references authors(ID),
  foreign key (GENRE_ID) references genres(ID)
);

CREATE TABLE comments (
  ID BIGSERIAL NOT NULL,
  TEXT VARCHAR(250) NOT NULL,
  BOOK_ID BIGINT,
  PRIMARY KEY (ID),
  foreign key (BOOK_ID) references books(ID) ON DELETE CASCADE
);

CREATE TABLE USERS (
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ENABLED SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES (
  USERNAME VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);